spring:
  datasource:
    url: jdbc:mariadb://i10a409.p.ssafy.io:5020/survey
    username: root
    password: KL1VERSE

server:
  ssl:
    enabled: true
    key-store: classpath:/keystore.p12
    key-store-type: PKCS12
    key-store-password: 1234
