spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A409
    username: S10P12A409
    password: kp7Ad1kzRN

#server:
#  ssl:
#    enabled: true
#    key-store: classpath:/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 1234