server:
  port: 8010

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    ssafy
    #    url: jdbc:mariadb://localhost:3306/dev
    #    username: root
    #    password: 1234

    #    home
    #    url: jdbc:mariadb://localhost:3307/dev
    #    username: root
    #    password: 1234

    #    remote
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/s10p12a409
    username: S10P12A409
    password: kp7Ad1kzRN

  # kafka 설정
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-group # 여기만 다름
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # redis 설정
  data:
    redis:
      host: i10a409.p.ssafy.io
      port: 6379
      password: redis

oauth:
  google:
    client-id: 651679120216-gedguefmg8lgjhi8vul42c48r9305mol.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/GoogleAuth
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    login-uri: https://accounts.google.com/o/oauth2/auth?client_id=651679120216-aedflji7ia436usf2vv2342hjkqnpmi8.apps.googleusercontent.com&redirect_uri=http://localhost:8080/login/oauth/code/google&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile&access_type=offline
  naver:
    client-id: eXJ_cTAVvlCn3lXE5sY6
    client-secret: YG20ejWAar
    redirect-uri: http://localhost:3000/NaverAuth/
    token-uri: https://nid.naver.com/oauth2.0/token
    resource-uri: https://openapi.naver.com/v1/nid/me
    state: 1234asdf
    login-uri:
  kakao:
    client-id: 4762e8102a9a8a8096d725c00ae8205d
    client-secret:
    redirect-uri: http://localhost:3000/KakaoAuth/
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me
    login-uri:


cloud:
  aws:
    s3:
      bucket: k-l1verse
    credentials:
      access-key: AKIA4X5JVVJBRX7QSL5G
      secret-key: 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
    region:
      static: ap-northeast-2

jwt:
  secretKey: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  # 배포
  accessExpirationTime: 3600 # 1시간
  refreshExpirationTime: 86400 # 1일
  # 로컬
#  accessExpirationTime: 10 # 10초
#  refreshExpirationTime: 60 # 60초