spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/s10p12a409
    username: S10P12A409
    password: kp7Ad1kzRN

  # kafka 설정 localhost 변경해야함.
  kafka:
    bootstrap-servers: i10a409.p.ssafy.io:9092
    consumer:
      bootstrap-servers: i10a409.p.ssafy.io:9092
      group-id: user-group # 여기만 다름
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: i10a409.p.ssafy.io:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  ssl:
    enabled: true
    key-store: classpath:/keystore.p12
    key-store-type: PKCS12
    key-store-password: 1234

oauth:
  google:
    redirect-uri: https://i10a409.p.ssafy.io/GoogleAuth
  naver:
    redirect-uri: https://i10a409.p.ssafy.io/NaverAuth/
  kakao:
    redirect-uri: https://i10a409.p.ssafy.io/KakaoAuth/

domain: https://i10a409.p.ssafy.io