server:
  port: 8000

spring:
  profiles:
    active: dev

#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: USER-LOGIN
#            uri: http://localhost:8010
#            predicates:
#              - Path=/user/**
#            filters:
#              - RewritePath=/user/(?<segment>.*), /$\{segment}

#          - id: USER-SERVICE-2
#            uri: http://localhost:8010
#            predicates:
#              - Path=/login/**
