server:
  port: 8000
#  ssl:
#    enabled: true
#    key-store: classpath:/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 1234

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-LOGIN
            uri: http://localhost:8010
            predicates:
              - Path=/user/**
            filters:
              - RewritePath=/user/(?<segment>.*), /$\{segment}

          - id: USER-SERVICE-2
            uri: http://localhost:8010
            predicates:
              - Path=/login/**
