server:
  port: 8030

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

#    ssafy
    url: jdbc:mariadb://localhost:3306/dev
    username: root
    password: 1234

    # remote
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A409
#    username: S10P12A409
#    password: kp7Ad1kzRN

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A409
#    username: S10P12A409
#    password: kp7Ad1kzRN

cloud:
  aws:
    s3:
      bucket: k-l1verse
    credentials:
      access-key: AKIA4X5JVVJBRX7QSL5G
      secret-key: 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
    region:
      static: ap-northeast-2

jwt:
  secretKey: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  # 배포
  accessExpirationTime: 3600 # 1시간
  refreshExpirationTime: 86400 # 1일
  # 로컬
#  accessExpirationTime: 10 # 10초
#  refreshExpirationTime: 60 # 60초

