spring:
  datasource:
    # 김동훈 ssafy
    url: jdbc:mariadb://localhost:3306/match_db
    username: root
    password: root

    # 김동훈 home
#    url: jdbc:mariadb://localhost:3307/dev
#    username: root
#    password: 1234