server:
  port: 8030

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

    # ssafy
    # url: jdbc:mariadb://localhost:3306
    # username: root
    # password: 1234

    # remote
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A409
    username: S10P12A409
    password: kp7Ad1kzRN

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A409
#    username: S10P12A409
#    password: kp7Ad1kzRN
#
