server:
  port: 8040

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update

  # redis 설정
  data:
    redis:
      host: i10a409.p.ssafy.io
      port: 6379
      password: redis
